# Generated by Django 4.2.3 on 2023-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='하위 업무 id')),
                ('team', models.TextField(verbose_name='하위업무 담당 team')),
                ('is_complete', models.BooleanField(default=False, verbose_name='하위 업무 완료 여부')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='업무 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업무 생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='업무 수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='업무 id')),
                ('team', models.TextField(verbose_name='하위업무 설정한 team list')),
                ('title', models.TextField(verbose_name='업무 제목')),
                ('content', models.TextField(verbose_name='업무 내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='업무 완료 여부')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='업무 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업무 생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='업무 수정시간')),
            ],
            options={
                'verbose_name': '업무 테이블',
                'db_table': 'task',
            },
        ),
    ]
