# Generated by Django 4.2.3 on 2023-08-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='업무 id')),
                ('team', models.TextField(verbose_name='하위업무 설정한 team list')),
                ('title', models.TextField(verbose_name='업무 제목')),
                ('content', models.TextField(verbose_name='업무 내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='업무 완료 여부')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='업무 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업무 생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='업무 수정시간')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='업무 생성한 user_id')),
            ],
            options={
                'verbose_name': '업무 테이블',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='하위 업무 id')),
                ('team', models.TextField(verbose_name='하위업무 담당 team')),
                ('is_complete', models.BooleanField(default=False, verbose_name='하위 업무 완료 여부')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='업무 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업무 생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='업무 수정시간')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='task id')),
            ],
        ),
    ]
